### ISSUE TITLE
Where is `igl.triangulate` in the new igl python package?

### ISSUE THREAD

**Issue by chaohuang** [libigl/libigl-python-bindings#102]
In libigl python package 0.3.1, I can call `igl.triangulate` to compute constrained Delaunay triangulations, but in the version 2.2.1, I cannot find `igl.triangulate` anymore. Is this function renamed or removed? Thank.

**Comment by danielepanozzo** [comment]
Yes, the triangulate function has been removed and it is not available in recent builds. The triangulate function in libigl is based on triangle, you can find other python wrappers online such as https://pymesh.readthedocs.io/en/latest/api_mesh_generation.html.

**Comment by chaohuang** [comment]
> Yes, the triangulate function has been removed and it is not available in recent builds. The triangulate function in libigl is based on triangle, you can find other python wrappers online such as https://pymesh.readthedocs.io/en/latest/api_mesh_generation.html.

Thanks for the response. I will try pymesh then, but do you mind to tell more about the rationale behind the triangulate function being removed in the newer version? Is it due to the license?

**Comment by danielepanozzo** [comment]
Yes, we want to avoid code with commercial or GPL-like licenses.  In the specific case of triangle, another reason is that the igl function was just a thin wrapper on top of an existing library, and was not adding any additional functionality.

**Comment by alecjacobson** [comment]
We should probably just add triangulate back. The GPL-like license already permeates most of the exposed bindings because of calls to Eigen's GPLed solvers.
