### ISSUE TITLE
topological_hole_fill Usege

### ISSUE THREAD

**Issue by kingui1106** [libigl/libigl-python-bindings#103]
I am use `topological_hole_fill ` ,and I see blow in Docs. So I wander how can i calculate the  `new abstract vertices `.
If there is any example, I would appreciate it very much
>Topological fill hole on a mesh, with one additional vertex each hole Index of new abstract
>vertices will be F.maxCoeff() + (index of hole)

**Comment by teseoch** [comment]
I think the function will add a new vertex per hole in the "center"
