### ISSUE TITLE
cannot find embree/rtcore.h when writing python binding 

### ISSUE THREAD

**Issue by iszihan** [libigl/libigl-python-bindings#109]
Hello, I'm trying to write a binding for one of the function that uses the embree intersector. I added the embree folder to both ./external and ./external/libigl/external. When I run python setup.py develop, I still get the error 

`/Documents/projects/libigl-python-bindings/external/libigl/include/igl/embree/EmbreeIntersector.h:23:10: fatal error: embree3/rtcore.h: No such file or directory
 #include <embree3/rtcore.h>`

I tried the following modification with CMakeLists.txt in the root directory, but none of them worked. 

- Add `target_include_directories(pyigl_classes PRIVATE "${PYLIBIGL_EXTERNAL}/embree/include")
`
- Change option(LIBIGL_WITH_EMBREE           "Use Embree"         OFF) to ON 

Much appreciated if someone can help to get rid of this error.

**Comment by alecjacobson** [comment]
In addition to 
```
option(LIBIGL_WITH_EMBREE "Use Embree" ON)
```

I believe you also need:

```
target_link_libraries(pyigl_classes PRIVATE npe igl::core igl::embree)
```

**Comment by iszihan** [comment]
Thank you! 

It now gives a new error saying 

```
-- Creating target: igl::core (igl)
-- Creating target: igl::predicates (igl_predicates)
CMake Warning (dev) at external/numpyeigen/cmake/numpyeigen.cmake:98 (set):
  Cannot set "NPE_ROOT_DIR": current scope has no parent.
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using eigen at /home/selenaling/Documents/projects/libigl-python-bindings/external/libigl/external/eigen
-- pybind11 v2.3.dev0
-- Configuring done
CMake Error at external/numpyeigen/cmake/numpyeigen.cmake:247 (add_library):
  Target "pyigl" links to target "igl::embree" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:66 (npe_add_module)
```
Am wondering if there is something else missing?

**Comment by alecjacobson** [comment]
Are you sure option(LIBIGL_WITH_EMBREE "Use Embree" ON)
is set to ON?

I believe this needs to appear in cmakelists.txt **_before_** any of the libigl related stuff.

(also try a clean build)

**Comment by iszihan** [comment]
A clean build worked! Thank you so much.

**Comment by alecjacobson** [comment]
Would love to start an `igl.embree` module if you'd like to PR your function. Closing this issue as resolved.
