### ISSUE TITLE
How to install on osx-arm64?

### ISSUE THREAD

**Issue by paddyroddy** [libigl/libigl-python-bindings#112]
Apologies, I'm aware that this is the last `stable` version but I just got a new laptop and now cannot install this great library. 

Clearly this is related to https://github.com/libigl/libigl/issues/1686. Is there a way and I can make the `setup.py` use header only mode if I compile from scratch i.e. https://github.com/libigl/libigl/issues/1686#issuecomment-955814180?

**Comment by paddyroddy** [comment]
The error I get after running `python setup.py develop` is like this
![image](https://user-images.githubusercontent.com/15052188/140656687-f3d0837d-ad82-4dff-96e3-d927f621ee2f.png)

**Comment by EJShim** [comment]
Is that latest merged PR indicates that I can install and use igl-python in M1 mac?

`conda install -c conda-forge igl` does not work for me now.

**Comment by paddyroddy** [comment]
That's what I thought, doesn't seem to work yet. Someone told me about the `conda-forge/conda-forge-pinning-feedstock` repo

**Comment by merlinyx** [comment]
Thanks for the post! It's very helpful. I just want to add that I think currently in setup.py it's possible to fail to get the corrent environment info.
https://github.com/libigl/libigl-python-bindings/blob/master/setup.py#L89
I would get errors like: 
> (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')

I changed this line to 
`        tmp = os.getenv("target_platform", "") + platform.machine()
`
and it worked out fine (added the correct cmake flag for osx arch).

**Comment by rubenwgs** [comment]
Are there any updates on this on how to install libigl via conda? igl is not found on the noarch or osx-arm64 conda repo, forcing the install via the osx-64 repo works but then obviously fails when trying to use libigl in python...

**Comment by alecjacobson** [comment]
fixed with #164 (use `pip install libigl`)
