### ISSUE TITLE
ValueError: Invalid dimension for argument v_init. Must have shape (#vertices, 2) for triangle mesh inputs.

### ISSUE THREAD

**Issue by successhaha** [libigl/libigl-python-bindings#113]
I made this error when using IGl.BBW.This is the code I used
b, bc = boundary_conditions(V, F, C, P, BE, CE)
    bbw = igl.BBW(0, 2)
    print(dir(igl.BBW))
    print("show", V, V.shape,F.shape,b.shape, bc.shape)
    W = bbw.solve(V[:, 0:2], F, b, bc)

['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'solve']
show [[ 48.         247.           0.        ]
 [ 32.         241.           0.        ]
 [ 23.         227.           0.        ]
 ...
 [122.14293226 139.11975114   0.        ]
 [ 74.31105382  94.1937588    0.        ]
 [ 83.24588549 136.3194767    0.        ]] (4285, 3) (8248, 3) (325,) (325, 16)
Traceback (most recent call last):
  File "C:/Users/123/Desktop/bbw_python-master/cloth_demo.py", line 136, in <module>
    W = bbw.solve(V[:, 0:2], F, b, bc)
ValueError: Invalid dimension. Argument V must have shape (#vertices, 3)

**Comment by alecjacobson** [comment]
I believe this should be fixed by https://github.com/libigl/libigl-python-bindings/pull/92 . If not, please reopen.
