### ISSUE TITLE
ModuleNotFoundError: No module named 'igl.pyigl'

### ISSUE THREAD

**Issue by JonathanPham** [libigl/libigl-python-bindings#114]
Hi,

I installed the source code via `python setup.py install`. But, when I ran `import igl` in Python, I got the error `ModuleNotFoundError: No module named 'igl.pyigl'`. It seems like the issue is coming from the command, `from .pyigl import *`, in `libigl-python-bindings/igl/__init__.py`.

Any recommendations on how to resolve this? Am I importing igl incorrectly in Python?

Thanks!

**Comment by fyviezhao** [comment]
I also met the same problem. Installing in a conda environment within a nivdia docker via `python setup.py install`.

**Comment by fyviezhao** [comment]
Would you please consider to release `v2.2.2` version of **conda libigl package**? I'm working on a 2D bbw project, and have to install libigl via `python setup.py install` since  the current  `v2.2.1` conda package had not fixed the 2D bbw assertion bug reported in #90. However, compiling libigl from scratch is error-prone as commented above. I'd appreciate if you could release a new conda version, which I believe will save my day and others who need 2D bbw.

**Comment by dawnfinzi** [comment]
I have also run into this error (whether I use a conda install or try and install from the source code). Unfortunately, the solution proposed above doesn't work for me, even though I am also working on a linux system. Any suggestions?

**Comment by kampelmuehler** [comment]
Also running into trouble with this currently - installed through `conda`, python 3.8.

**Comment by ntraut** [comment]
I don't know why but the libraries were not copied after in the imported `igl` directory after I did `python setup.py install`. To fix that issue, I had to manually copy them. In my case:
```
cp build/lib.macosx-11.1-arm64-3.9/igl/*.so igl
```

**Comment by dyy0205** [comment]
> I have also run into this error (whether I use a conda install or try and install from the source code). Unfortunately, the solution proposed above doesn't work for me, even though I am also working on a linux system. Any suggestions?

hi, have you solve this problem?

**Comment by ntraut** [comment]
> hi, have you solve this problem?

in my case yes, you have to know in which folder igl is running and manually copy the libraries there if the installation script did not do it.

**Comment by alecjacobson** [comment]
I'm hoping this problem may have been solved with the migration to pip (`pip install libigl`). If this is still an issue, please reopen.

**Comment by santisy** [comment]
> 

Thanks. Copying the compiled files solved my issue.
