### ISSUE TITLE
Segmentation Fault during Gradient Computation

### ISSUE THREAD

**Issue by avaruuser** [libigl/libigl-python-bindings#115]
Hi all,

I want to compute the gradient of data defined on an open surface mesh. However, during computation of the gradient with `igl.grad(v, f)` I get the error message 

`[1]    76382 segmentation fault  python script.py`

I had the suspicion that this error might occur because the gradient cannot be computed on an open mesh, so I computed the gradient on the corresponding closed surface mesh but I got the exact same error message.
I also tested the gradient computation on a simple spherical mesh and that worked. Therefore, I guess it must be my specific mesh. Are there any constraints on what the mesh needs to look like? I used a triangulated surface mesh. Does it need to be convex?

I would appreciate any help with this.

**Comment by alecjacobson** [comment]
Gradients are computed per-triangle, so an open mesh is no problem. The surface does not need to be convex. If you'd like to reopen, please post your troublesome mesh.
