### ISSUE TITLE
Feature request: Oriented Minimum Bounding Box

### ISSUE THREAD

**Issue by mhelmrei** [libigl/libigl-python-bindings#117]
Hello,
thank you for sharing this library.

I was wondering is there a function that calculates the minimum bounding box around a given
set of vertices? The current bounding box function seems to align the bounding box to the
world coordinate system.

thank you. matthias

**Comment by alecjacobson** [comment]
This library exclusively creates python bindings for existing functionality in the C++ libigl library, which does't support OBB. However, this is a cool feature request for [libigl](http://github.com/libigl/libigl). Feel free to make an issue or PR on libigl.
