### ISSUE TITLE
Marching cubes binding included but missing from documentation

### ISSUE THREAD

**Issue by sgsellan** [libigl/libigl-python-bindings#118]
This repository includes a binding for the libigl `marching_cubes.cpp` implementation; however, it is not stated so in the [repo's documentation](https://libigl.github.io/libigl-python-bindings/igl_docs/), where no such function is mentioned

**Comment by sgsellan** [comment]
nvm, realized it is not in the latest pip/conda issue

**Comment by sysuyl** [comment]
Hi, [sgsellan](https://github.com/sgsellan),

No igl.marching_cubes in current latest igl version(2.2.1). When will you update the conda package to include the marching cubes?
