### ISSUE TITLE
Buggy offset_surface

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl-python-bindings#120]
From email:

> I’m using libigl in a jupyter notebook, so far so good.
> 
> But, struggling with the output from the “offset_surface” function:
> 
> out = igl.offset_surface(v_scaled, f, isolevel=10, s=200, signed_distance_type=3)
> 
>  
> 
> 1. Output is not as smooth as I would expect. Seems like it is layered.
![image002](https://user-images.githubusercontent.com/2241689/148699259-063ea9da-f4ae-4c97-a8a8-686ba04fac11.png)
> I guess this is related to “Compute a triangulated offset surface using matching cubes on a grid of signed distance values from the input triangle mesh.”
> As mentioned, I’m a newbe. So don’t quite understand what this algoritm does.
> As far as I can digest, it doesn’t offset the face triangles with isolevel signed distance on “per_face_normals”, as I hoped it would.
> 
> 2. I use a positive “isolevel”, to create a model that is larger/external to the original geometry.
> But plotting the original model and the “offset_surface” SV as pointclouds, also shows an internal (negative “isolevel” ?) geometry.
> “So #GV by 3 list of signed distance values near isolevel (“far” from isolevel these values are incorrect)”
> In this case GV is a (6407800, 3) matrix with positive and negative values. Don’t understand this matrix, since it’s not required to plot the results.
> 
> 3. The parameter “signed_distance_type” (0, 1, 2 or 3) doesn’t change the output, as far as I can  tell.

**Comment by alecjacobson** [comment]
1. This is fixed by https://github.com/libigl/libigl-python-bindings/commit/a21af9f57ba7e418ea9e120f2b1bf4e6d11286bb (The isolevel and output signed distances were accidentally using `int` and should have been `double` in the python bindings. This is now fixed.)
2. You were using `3` for the signed distance type. This corresponded to `igl.SIGNED_DISTANCE_TYPE_UNSIGNED` so the inner and outer layers are expected. I recommend you switch to `igl.SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER` when you have a meaningful inside and outside.
3. Theoretical they should all be the same _except_ for `igl.SIGNED_DISTANCE_TYPE_UNSIGNED`. For those that use sign, `igl.SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER` and `igl.SIGNED_DISTANCE_TYPE_FAST_PSEUDONORMAL` are the fastest and `igl.SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER` and `igl.SIGNED_DISTANCE_TYPE_WINDING_NUMBER` are the most robust.

**Comment by alecjacobson** [comment]
For posterity here is my testing script and output

```
import igl
import numpy as np
import polyscope as ps
[V,F] = igl.read_triangle_mesh('bunny-remesh.obj')
isolevel = np.linalg.norm(V.max(0)-V.min(0))*0.05
[OV,OF,_1,_2,_3] = igl.offset_surface(V,F,isolevel,100,igl.SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER)
ps.init()
ps.register_surface_mesh("original",V,F)
ps.register_surface_mesh("offset",OV,OF)
ps.show()
```
<img width="1392" alt="Screen Shot 2022-01-09 at 3 19 57 PM" src="https://user-images.githubusercontent.com/2241689/148699595-a37bb136-00ae-4103-bb60-65e89670def5.png">
[bunny-remesh.obj.zip](https://github.com/libigl/libigl-python-bindings/files/7835868/bunny-remesh.obj.zip)

**Comment by im44pos** [comment]
Hi Alec, 
thanks for solving point 1.

On 2. and 3. I get an AttributeError:
----> 5 [OV, OF, _1, _2, _3] = igl.offset_surface(V, F, isolevel, 100, igl.SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER)

AttributeError: module 'igl' has no attribute 'SIGNED_DISTANCE_TYPE_FAST_WINDING_NUMBER'

If I try: out = igl.offset_surface(V, F, isolevel, 100, signed_distance_type = 1)
I get:
TypeError: offset_surface(): incompatible function arguments. The following argument types are supported:
    1. (v: array, f: array, isolevel: int, s: int, signed_distance_type: int) -> Tuple[object, object, object, object, object]

I was not able to update the igl package in the anaconda environment.
So I created a new environment and performed a fresh installation, but package has same version (2.2.1) as before.

I also noticed that the documentation is still the same as before.

What should I do? Or is it something you can resolve?


Kind regards.

**Comment by alecjacobson** [comment]
I'm guessing that this means that you aren't using the newly compiled version. I'm not sure the best way to do this. If you run your code from the `libigl-python-bindings` directory then I believe `import igl` will use the compiled one there. Which you can verify by looking at `igl.__file__`.

**Comment by im44pos** [comment]
Took some internet searching to understand what to do; now it works.

Is there a paper related to this offset_surface function? Would like to better understand how this algorithm works.

**Comment by alecjacobson** [comment]
This function is making a regular grid around the input mesh. Computing signed distance values at each grid node and then running an algorithm called "Marching Cubes" to extract the `isolevel` level set. Distances are computed using an "Axis aligned Bounding Box" tree. (there are wikis for these terms which are fairly standard now).
