### ISSUE TITLE
python setup.py develop tries (and fails) to build scipy from source

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl-python-bindings#129]
I didn't originally have scipy installed. The `python setup.py develop` seemed to attempt to download and build scipy from source leading to all sorts of missing dependency and compilation errors. This is easily avoided by first installing scipy (and the documentation could be improved on that via #126).
Meanwhile, why does the script try to build scipy? Is that for the conda deployment?

**Comment by teseoch** [comment]
it shouldn't, i think it is a pybind11 thing with sparse matrices. I agree scipy should be installed before

**Comment by alecjacobson** [comment]
This should now be solved by `pip install ./` (via `pyproject.toml`). I'm not 100% sure that's working and working well for `setup.py develop` but I'm guessing this issue is related to conda messiness.
