### ISSUE TITLE
igl.point_mesh_squared_distance produces Error: Numerical issue. Error: invalid solver type

### ISSUE THREAD

**Issue by tlk13** [libigl/libigl-python-bindings#135]
Hello all, 

I am trying to use igl.point_mesh_squared_distance to calculate distances of my mesh points to polylines that I created beforehand. My code works for certain polylines but for others it inexplicably does not work. 

`_, closest_faces, closest_points = igl.point_mesh_squared_distance(polylines[i], pts, faces)`

This is how I use the function. 

My arguments are: 

`polylines[i]` = Mx3 numpy array, with each point saved in a numpy array of length 3 and encoded as 3 float values 
`pts` = Nx3 numpy array, with each point of the mesh saved in a numpy array of length 3 and encoded as 3 float values 
`faces` = Ex3 numpy array with each edge encoded as 3 integers referring to the points that make up one triangle 

For some polylines, I get good results, such as below: 

<img width="694" alt="Screen Shot 2022-03-09 at 15 25 36" src="https://user-images.githubusercontent.com/36789465/157461139-1844ed3e-1b01-491a-ab40-340a9b1e0107.png">

For others however, there Numerical issue and invalid solver type is raised. The results are as follows: 
<img width="694" alt="Screen Shot 2022-03-09 at 15 25 46" src="https://user-images.githubusercontent.com/36789465/157461252-8f92b2e7-0937-47ec-a329-44d0459faa8f.png">

There is no real difference between the two polylines. They both lie on the surface of the mesh. 

When I apply a transformation on the points as in the above image, such as this: 

`points_simple[:,0] *= 1.4`, occasionally, no error is raised. However, I still do not get the result I want, as the resulting array for the distances is simply filled with NaNs. 

What am I doing wrong, or is the code simply not working?

**Comment by alecjacobson** [comment]
Your usage seems correct so it's disturbing that this is raising an error. Please include your troublesome input data to debug and reopen this issue (closing due to age and not enough information).
