### ISSUE TITLE
Buggy winding_number

### ISSUE THREAD

**Issue by im44pos** [libigl/libigl-python-bindings#137]
Playing with the winding_number function in a jupyter notebook to understand what is does and check if I can use it on a triangular mesh. I started with an icosahedron around the origin (so the origin O is centered inside), then igl.winding_number(V, F, O) results in (1.) as expected. Next I used a point outside the icosahedron resulting in (0.) as expected. 

Then I computed the barycenter coordinates with igl.barycenter(V, F), and used this array (BcC) to compute the windingnumbers for each barycenter coordinate. Would expect similar results for all barycenter coordinates, but got 8/20 to be exactly 1.00000000e+00 and 12/20 to be something like -3.46944695e-17 (11/20 are negative, 1/20 is positive).

Next I computed the barycenter coordinates with a per face normal offset to have all points outside the icosahedron, computing the windingnumbers which results in 12/20 to be 0.00000000e+00 and 8/20 to be something like -3.46944695e-17 (5/20 are negative, 3/20 is positive). They should all be 0.00000000e+00 because all points are clearly offset from the faces.

So I checked by computing the windingnumbers for the barycentercoordinates when using the same offset distance but now all point are clearly inside the icosahedron: result all 20/20 point have windingnumber 1.

**Comment by alecjacobson** [comment]
All of this seems correct behavior to me. Winding number computation uses floating point arithmetic, so treat -1e-17 as 0.0. Theoretically, points on the surface of a mesh have a winding number somewhere between [0,1] (e.g., ½ for face barycenters), however, these points lie within the singularity of the winding number and would require special handling that this code doesn't do.

**Comment by im44pos** [comment]
Thanks for clarifying.
