### ISSUE TITLE
`igl.principal_curvature` fails with Segmentation fault

### ISSUE THREAD

**Issue by Sentient07** [libigl/libigl-python-bindings#152]
Hi,

I've a selected few meshes where `principal_curvature` computation fails. It's unclear why as there are no tracebacks. Some of these failure meshes are `'00003432', '00007948', '00000114', '00003388', '00003438'` from the instance 1 of the ABC dataset. Can someone please help me understand why it would fail?

Thanks

**Comment by alecjacobson** [comment]
Could be an issue reading .stl files without merging vertices. https://github.com/libigl/libigl-python-bindings/issues/96#issuecomment-1416784196

Please consider reopening with a minimal example of your code and a model that fails.
