### ISSUE TITLE
Abandon conda → pip+cibuildwheel

### ISSUE THREAD

**Issue by alecjacobson** [libigl/libigl-python-bindings#158]
Conda seems hard to update as we make changes and isn't building for modern macs.

After some conversations with developers of other python binding libraries, it seems a better route would be to switch ti [CIBuildWheel](https://cibuildwheel.readthedocs.io/en/stable/) and pip.

Would be great to make some progress on this after the SIGGRAPH deadline. If anyone has more experience, I might need a hand.

meanwhile, building from source _does_ work on arm macs via:

    pip install git+https://github.com/libigl/libigl-python-bindings/

**Comment by alecjacobson** [comment]
At first glance this doesn't look that bad. I'm testing things out over here https://github.com/alecjacobson/libigl-python-bindings/ so I can try setting up the github actions (not sure if I could have done that on a branch for this fork).

**Comment by BruegelN** [comment]
related to #45 

@alecjacobson I've started a similar effort a while ago (https://github.com/BruegelN/libigl-python-bindings) but can't recall why I got stuck.... The only thing I remember is that every shot took quite some time.
I'll look into it again during the next week(s) :slightly_smiling_face:

**Comment by alecjacobson** [comment]
thanks, Nico. Indeed these builds take forever. I almost wonder if it's worth creating a for that just has a single function wrapper like `igl.read_triangle_mesh` or something and then getting the whole CI → PyPI workflow in place.

**Comment by alecjacobson** [comment]
I've successfully created a cibuildwheels github action and pushed to PyPi

https://pypi.org/project/libigl/0.0.3/

install with

    pip install libigl

Would be great to battle-test this a bit before announcing it (and I'd propose abandoning conda).

**Comment by alecjacobson** [comment]
Thanks for testing it! 

So far, I've also had good success. I picked up an old mac laptop and figured I'd just see what happens when I did `pip install libigl`. Immediately worked. What a big change from conda.
