### ISSUE TITLE
Tutorial 0: NameError: name "displav' is not defined

### ISSUE THREAD

**Issue by JasonLiu2024** [libigl/libigl-python-bindings#161]
Hi! I cannot get Tutorial 0 to work because 'display' is not defined. Here are screenshots of what happened: (I'm using Pycharm, newest version of Python and Libigl, just installed)
<img width="1268" alt="Screen Shot 2023-01-03 at 8 55 42 AM" src="https://user-images.githubusercontent.com/89846549/214679164-27756892-968e-43aa-8ee8-ce1060336ccd.png">
<img width="1114" alt="Screen Shot 2023-01-03 at 8 55 19 AM" src="https://user-images.githubusercontent.com/89846549/214679171-486f3da0-4a16-4021-9d4e-225c1822b758.png">

**Comment by alecjacobson** [comment]
This appears to be a meshplot issues, not a libigl or libigl-python-bindings issue. Closing and would encourage to transfer to https://github.com/skoch9/meshplot/issues

see, e.g.,  https://github.com/skoch9/meshplot/issues/11
