### ISSUE TITLE
Update docs & tutorials according to new pip installation method

### ISSUE THREAD

**Issue by BruegelN** [libigl/libigl-python-bindings#176]
The docs hosted on https://libigl.github.io/libigl-python-bindings/ (generated from `tutorial/`) still mention installation process via conda and contain quite a lot of references/badges from anaconda.

@alecjacobson somehow I can't assign myself, feel free to assign it to me. I'll try to dig into the mkdocs thing through the course of this week :)

**Comment by BruegelN** [comment]
I've noticed that both [tutorial/tutorials.ipynb](https://github.com/libigl/libigl-python-bindings/blob/5f53a3a52a46d30494875a157d66d9c853dc7266/tutorial/tutorials.ipynb)  and [tutorial/tut-chapter7.ipynb](https://github.com/libigl/libigl-python-bindings/blob/5f53a3a52a46d30494875a157d66d9c853dc7266/tutorial/tut-chapter7.ipynb) aren't on https://libigl.github.io/libigl-python-bindings/. They're not even included in `mkdocs.yml`.  The former is actually no a valid notebook file. Should they be part of the docs or not? I'll leave them aside for now.

**Comment by BruegelN** [comment]
Hi @alecjacobson,

I'd like to use this issue to keep track of the things that need to be done to update and improve the docs.
Once #187 (just the code) is merge one can merge #192 (gh-pages) to actually update the docs.

After a somewhat recent version of the docs are online I'll proceed with versioned docs. Once I've figured that out I'll create another MR.

**Comment by alecjacobson** [comment]
I believe this all got merged correctly. Please reopen if I screwed it up.
