### ISSUE TITLE
Binding for Python27

### ISSUE THREAD

**Issue by daphna-kaplan** [libigl/libigl-python-bindings#200]
It is not motioned in the documentation which python versions are supported.
However, if I am in need of using python2.7, what are my options?
(normal pip install fails)

**Comment by alecjacobson** [comment]
I think there's no hope get the entire library of bindings compiled. Pybind11 also does not support python versions from so long ago. And we depend heavily on pybind11. If you have to use 2.7 and you want to use a libigl function from Python, then you might create a special wrapper just for that one function. I'm not sure how to do that. Good luck

**Comment by alecjacobson** [comment]
Closing for now. Feel free to reopen if there's more to discuss.
