### ISSUE TITLE
Implementation for NRosy

### ISSUE THREAD

**Issue by royvelich** [libigl/libigl-python-bindings#204]
Hi,
I want to use `igl.nrosy` but it seem to be not available. What's the status of it? You do mention it in the python tutorial notebook though.
Are there any alternatives that I can use for Python?
Specifically, I would like to replicate https://github.com/libigl/libigl/blob/main/tutorial/505_MIQ in python.

Thanks

**Comment by alecjacobson** [comment]
I'm personally not going to implement this binding but would be happy to merge a PR.

**Comment by alecjacobson** [comment]
The comiso module in libigl hasn't had a maintainer for a while. It will probably be deleted soon. I recommend looking at https://github.com/avaxman/Directional/ or other libraries.
