### ISSUE TITLE
Error: Numerical issue with ARAP

### ISSUE THREAD

**Issue by HansVansWardikins** [libigl/libigl-python-bindings#210]
Hello, 

I am attempting to flatten a mesh using your wonderful toolkit, more specifically the ARAP parametrization tool. I don't have a mathematical background nor much experience with coding so please forgive me if I approach anything here with the wrong nomenclature or best practice.

Here is the mesh I am testing the code with: 
[test.zip](https://github.com/libigl/libigl-python-bindings/files/12684438/test.zip)

I have been playing with code copied from the Python Bindings tutorial chapter 4, this is the code that currently gives me the numerical error:

[ARAP - Copy.zip](https://github.com/libigl/libigl-python-bindings/files/12684497/ARAP.-.Copy.zip)
![image](https://github.com/libigl/libigl-python-bindings/assets/145659314/e12b5657-b966-4804-aafd-8813a8026948)

It runs but gives the following response:
![image](https://github.com/libigl/libigl-python-bindings/assets/145659314/5a943822-52e2-4fff-9565-b06912be74d2)

and the 2D plot produces nothing.

I have also tried using only the harmonic parametrization which seems to work perfectly but it is really the ARAP parametrization I am interested in.

I would really appreciate it if someone were able to consider this issue for me and share their experience with me on how I might go about solving it.

Thanks in advance
Alex

**Comment by alecjacobson** [comment]
I'm not super familiar with the python interface to ARAP but it seems like a couple things are off:

you gotta call `ARAP.precomputation` before you call `ARAP.solve`

When you call `ARAP.precomputation` you should specify which vertices (by index) will be fixed.

During ARAP.solve you should specify the desired positions for those vertices.

**Comment by HansVansWardikins** [comment]
Hi Alec,

Thank you for getting back to me. I don't know if am missing something simple or not but I don't see a function for ARAP.precomputation... In the docs or in my Python editor.

Are you able to provide any further information?

Thanks
Alex

**Comment by HansVansWardikins** [comment]
Hi again Alec,

I really appreciate your input on this.

I am still confused about the usage of the parameters **b** in **igl.ARAP** and **bc** in **arap.solve** when used for surface parametrization.

In both the Python and the C++ tutorials on ARAP parametrization, zeros are used for  **b** and **bc**, this would indicate to me that no boundary conditions are implied and the mesh is allowed to freely deform in space to minimize deformation energy, maybe that is a wrong assumption?

Anyway, I seem to have overcome the **Error: Numerical issue** for now, I noticed from [Example 503](https://github.com/libigl/libigl/tree/main/tutorial/503_ARAPParam/main.cpp) of the C++ tutorial, that when the ARAP precomputation is called, a parameter **with_dynamics** is set to true, with the comment "Add dynamic regularization to avoid to specify boundary conditions". Maybe this is also meant to be in the Python tutorial? I fixed my code by adding the kwarg **with_dynamics = True** to my initialization of the ARAP class:
![image](https://github.com/libigl/libigl-python-bindings/assets/145659314/d1703c60-ebf3-48b5-8669-7edbe40b46d7)
![image](https://github.com/libigl/libigl-python-bindings/assets/145659314/3c7301f7-829d-4d87-89b2-4601bc89e30b)

I must admit I don't really understand the implications of this on how the ARAP algorithms are applied but I am happy it gives me something that works for me to experiment with.

Best regards
Alex

**Comment by HansVansWardikins** [comment]
Thanks for your consideration Alec. I think I can mark this as closed now. I have another question but I will post that under a separate thread.
