### ISSUE TITLE
remove_duplicates

### ISSUE THREAD

**Issue by JianlayWang** [libigl/libigl-python-bindings#218]
In the documentation of libigl-python-bindings, `remove_duplicates() `can be used to remove duplicate points in the mesh and update the face of the mesh. However, when I actually called it, I found that there does not seem to be this function. Has it been deleted?
![image](https://github.com/libigl/libigl-python-bindings/assets/138512306/2657f5a6-a5fb-4889-a87e-ca6249beae5f)

**Comment by alecjacobson** [comment]
yup, please use `igl.remove_duplicate_vertices`
