### ISSUE TITLE
How to use igl.cut_mesh(v: array, f: array, cuts: array)

### ISSUE THREAD

**Issue by Wolf1024Hzx** [libigl/libigl-python-bindings#227]
I created a very simple closed model:
```
v 0.0 1.0 0.0
v 1.0 -1.0 0.0
v -1.0 -1.0 0.0
v 0.0 0.0 1.0

f 1 2 3
f 1 2 4
f 1 3 4
f 2 3 4
```
And then input the cuts array as:
[[1 1 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
The program seems to enter into an infinite loop and eventually throws the error 'MemoryError: bad allocation'. 

Could you please help me understand what's happening?😢

**Comment by Wolf1024Hzx** [comment]
when I input the model like:
```
v 1.0 1.0 1.0
v -1.0 1.0 1.0
v -1.0 -1.0 1.0
v 1.0 -1.0 1.0
v 0.0 0.0 0.0

f 1 2 5
f 1 4 5
f 2 3 5
f 3 4 5
```
and input the cuts array as:
[[0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]]

I just want to cut the edge (v0, v4) in this picture:
![photo](https://github.com/libigl/libigl-python-bindings/assets/72795347/68522829-ad5b-4911-983a-3c57345683bf)

the vcuts and fcuts which the function returned are:
vcuts:
[[ 1.  1.  1.]
 [-1.  1.  1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
fcuts:
[[0 1 5]
 [0 3 6]
 [1 2 5]
 [2 3 5]]
but the index of 6 is out of range, could you help me solve this problem?😢

thank you very much!!

**Comment by alecjacobson** [comment]
Hi, your inputs need to be consistently oriented. For example, the faces of your  first mesh are not all counter-clockwise oriented:

```
f 1 2 3
f 1 2 4
f 1 3 4
f 2 3 4
```

If you switch it to a properly oriented mesh like:

```
f 1 2 3
f 1 3 4
f 1 4 2
f 2 4 3
```
then it should work.

**Comment by Wolf1024Hzx** [comment]
thank you!
