### ISSUE TITLE
igl.ARAP crashes

### ISSUE THREAD

**Issue by royvelich** [libigl/libigl-python-bindings#238]
Hi,
I try to run the exact example given in [ARAP](https://libigl.github.io/libigl-python-bindings/tut-chapter3/#as-rigid-as-possible) (with the same data files), but Python crashes with `Process finished with exit code -1073741819 (0xC0000005)`.

Does it work for anyone else?
Do you have any ideas on what I can do?

It crashes on both Windows and Ubuntu. I install libigl through pip.

Thanks

**Comment by alecjacobson** [comment]
not sure if it's related to this issue, but currently libigl will not work with numpy>=2.0.0

**Comment by PhilFreeman** [comment]
I'm using numpy 2.1.3, and haven't had an issue other than ARAP. But I'll set up a venv with a lower numpy and see if that resolves it.
As a work around, I switched to LSCM and that works fine.
