### ISSUE TITLE
missing important bindings

### ISSUE THREAD

**Issue by teseoch** [libigl/libigl-python-bindings#24]
- [x] HalfEdgeIterator.h
- [x] hessian_energy.h
- [x] min_quad_with_fixed.h
- [x] shapeup.h
- [x] slice_tets.h
- [x] offset_surface
- [x] miq
- [x] marching tets

**Comment by KarlLeell** [comment]
hessian_energy added back. There are some changes in libigl which may have some impact I'm not sure, please refer to commit 465ad7c9c4f52458861e6395e959bd969487475e and 32e836670259ca040bbc74fff03c4b16070f0100.

**Comment by teseoch** [comment]
Let’s leave the half edge iter to Francis that wants to do something fancy

**Comment by teseoch** [comment]
miq requires comiso which has problems as nrosy

**Comment by teseoch** [comment]
- marching_cubes - This function takes a grid array in a really annoying format because Eigen only supports 2-tensors. Ideally you should be able to pass in data stored in a 3D arrray.

**Comment by r03ert0** [comment]
Would it be possible to make available also the boolean operations?

**Comment by teseoch** [comment]
The boolean operations depend on cgal, which is not MPL.
For this reason we dont plan to include them in the conda version of the binding.
We however plan (in a distant future) to add them and let users build the bindings.

Long story short, boolean operations have low priority.
That being sayed, we are also developing another conda library (wildmeshing) which has robust boolean. You can check the tutorial here:
https://wildmeshing.github.io/wildmeshing-notebook/

**Comment by AlbertoMQ** [comment]
Hello, has the python shapup binding been implemented?

**Comment by teseoch** [comment]
yes, in the development version

we plan to release conda in a couple of months

**Comment by teseoch** [comment]
I just added Volume, also only in the dev version

**Comment by daviesthomas** [comment]
> * marching_cubes - This function takes a grid array in a really annoying format because Eigen only supports 2-tensors. Ideally you should be able to pass in data stored in a 3D arrray.

@teseoch is anyone working on this actively? I need marching cubes exposed in python bindings for a project and can look into this. Don't want to duplicate any code!

**Comment by teseoch** [comment]
Sure we are still working on it. 

The problem with marching (in addition of using tensors) is that the algorithm is copyrighted, so including that function will require to change the license of the python package

**Comment by daviesthomas** [comment]
Ahh okay. Are you wanting to avoid the change in license or is that simply a comment? 

My plan for marching cubes was to allow a volumetric grid as input which we then transform into the correct format for igl::copyleft::marching_cubes strange input requirements. This would happen within the function and would not be visible (from usage perspective) to the user.

**Comment by teseoch** [comment]
I don't think we can just comment.
If you know exactly how to include that function without polluting the open license let me know

In the meantime, you can use marching tet which is not copyrighted
