### ISSUE TITLE
can't access signed_distance function

### ISSUE THREAD

**Issue by celinede** [libigl/libigl-python-bindings#31]
Hi !
I have successfully installed the librairy with conda and could use without any problem, read_triangle_mesh() or adjacency_matrix() but I can't find signed_distance()
Is there any trick to be able to use this function ?
Thanks for your help !
Céline

**Comment by fwilliams** [comment]
What version of `igl` do you have installed? (You can check with `conda list igl`). With version `0.4`, I can call `igl.signed_distance` without any issues.

**Comment by celinede** [comment]
Thank you very much ! I have updated the library and I now have access to it.
It is a bit unexpected to not get the last update when installing with:
 conda install -c conda-forge igl
I had version 0.1

**Comment by fwilliams** [comment]
You should always get the latest update when installing with conda! Check your setup. We just pushed 0.4 last week.
