### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by roaasoloh** [libigl/libigl-python-bindings#37]
applying principal curvature using the command:

`
v1, v2, k1, k2 = igl.principal_curvature(v, f)
`

but I'm getting the error:

`
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
`

v are in this format:

`
[[ 56.09962091 -50.70284252 74.43154099] [ -81.66580634 31.11304083 -96.20692408] [ -63.04710378 20.05579935 -73.14550082] [ -74.68074967 -46.74132945 -125.53300517] [ -82.86191115 138.50006684 4.60130311] [ 73.56470904 -118.43376944 -71.32137773] [ -4.92233919 -159.90066014 -27.83674232] [ -75.62714176 28.23358687 -78.90299045] [ -81.53924671 121.62689731 52.15735424] [-119.16738782 84.67573099 64.81959086] [ 115.65943449 -56.67805099 -75.6967053 ] [ -80.48401851 20.7915225 -68.63223673] [-142.29170674 -108.38603014 -36.96969018] [ 98.64894284 50.12674432 58.67070153] [ -28.13477169 83.20510976 107.46559988] [-144.66277425 68.30107727 49.66061848] [ 29.54206082 143.22321321 -55.06127287] [ 4.90252259 69.73588386 -132.70296423] [-102.13321016 -67.17764799 -111.93319288] [-166.21385932 13.10544553 -15.81392708] [ -38.58577129 144.34755316 28.37260346] [ 56.31233339 -61.38765368 64.17787867] [ -90.93979735 0.38020425 -79.89511472] [ -96.76884596 21.71346256 -64.96037686] ... [ 74.58292415 -124.48759489 -5.62172548] [-174.78859069 -11.99712938 -11.00922369] [ 87.27561955 69.94477948 -108.91576776] [ 117.33246385 -69.39698438 16.03177459] [ 103.92915334 60.71174874 -89.2834191 ] [ 11.60050005 104.17767979 85.44092131] [ 45.99420387 -75.99419561 -145.5603443 ] [ -75.78031523 8.32746322 -78.40591649]
`

and f are:

`
[[ 0 165 425] [ 0 836 165] [ 0 128 836] [ 0 107 128] [ 0 542 107] .. [ 0 425 164] [425 120 834] [425 165 120] [165 726 120] [165 836 726]
`

As well if I used the gaussian curvature it prints out the results but with giving nan values!!!

`
[ nan 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 3.15422311 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 3.14159265 nan 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
`

as well as the error in the title.
I guess it's important to mention that I'm extracting curvature on feature points of the mesh, not the complete vertices.
Please any help!

**Comment by caniko** [comment]
Why did you close the issue?
