### ISSUE TITLE
Interface (buttons/picking vertices)

### ISSUE THREAD

**Issue by MichaelRabinovich** [libigl/libigl-python-bindings#39]
Hey all,

The new python bindings looks awesome!
It might be a pretty dumb question, but you removed the old viewer from the newer python bindings right? Is there still a way to pick vertices, and add a menu? Some easy way to get most/all functionality available in the C++ code or old python version?

Thanks!

**Comment by teseoch** [comment]
we are not planning to add to the viewer to the current bindings

the current bindings are compatible with NumPy so you can use any python library.

I know of a project that is emulating the current viewer using Qt:
https://github.com/sunreef/PyIGL_viewer

**Comment by fwilliams** [comment]
If you're looking for a top notch 3D viewer in Python. [Mayavi mlab](https://docs.enthought.com/mayavi/mayavi/mlab.html) is fantastic!

You can install it through conda with
```
conda install -c anaconda mayavi
```

(The conda method works on all platforms while I've found the instructions on the website only really work on Linux)

**Comment by MichaelRabinovich** [comment]
Thanks!
Both of the projects looks really nice, but none gives the full set of features the previous viewer had (for instance textures support, picking vertices).

I saw that the old python bindings will be removed from next libigl versions. This means that the new python bindings could not run out of the box most tutorials, right?

I'll be interested in hearing what the developers of libigl use. I guess some don't need certain interactive tools that exist in the C++ version, but also that some do.

**Comment by skoch9** [comment]
For the [official tutorials](https://libigl.github.io/libigl-python-bindings/tutorials/) we use [meshplot](https://github.com/skoch9/meshplot).
You can check out the [binder](https://mybinder.org/v2/gh/libigl/libigl-python-bindings/master?filepath=tutorial%2Ftutorials.ipynb) for an interactive session. Meshplot supports textures and interactivity and picking is added soon.

**Comment by fwilliams** [comment]
You can do texturing in Mayavi: [Here's an example](https://gist.github.com/leon-nn/f284a26a45a92b17b6d8315d8327ceb5).
