### ISSUE TITLE
principal_curvature crash

### ISSUE THREAD

**Issue by GentleDell** [libigl/libigl-python-bindings#40]
Hello all,

I would like to use the python binding to compute mean curvatures of a point cloud. 

However, when I go through this [tutorial](https://libigl.github.io/libigl-python-bindings/tutorials/) with the [bunny point cloud](https://github.com/libigl/libigl-tests-data), I find the function principal_curvature() always make the python kernel crash while gaussian_curvature() works properly.

I use the same codes as the Tutorial-igl, i.e:
`
v, f = igl.read_triangle_mesh(os.path.join(root_folder, "bunny.off"))
v1, v2, k1, k2 = igl.principal_curvature(V, F)
`
I tried with other point clouds, such as the 4 points in the tutorial but it does not work either.

So, I was wondering how I could use the function to compute curvatures correctly. 

My system information:
Ubuntu ---- 18.04
python  ---- 3.7.6
igl         ---- 0.4.1     py37h6dc7ae4_0    conda-forge (install with : _conda install -c conda-forge igl_)

Thank you very much for your time.

Best regards,

**Comment by teseoch** [comment]
I tried on mac and it works

@fwilliams maybe you can try on linux?

**Comment by fwilliams** [comment]
Hey the following code works for me with the same OS and versions as you
```python
v, f = igl.read_triangle_mesh("bunny.off")    
igl.principal_curvature(v, f) 
```

One thing I noticed is that you typed `v1, v2, k1, k2 = igl.principal_curvature(V, F)` with inputs `V` and `F` (upper case) but you loaded the mesh with `v, f = igl.read_triangle_mesh(os.path.join(root_folder, "bunny.off"))` (using lower case `v` and `f`). Maybe `V` and `F` were declared somwhere else in your notebook and you're passing in an invalid mesh to `principal_curvature`.

**Comment by GentleDell** [comment]
Hello @fwilliams

Thank you very much for your time and reply. 

You are right that I use the wrong variable. Now the igl works perfectly.

Thanks again for your patient.

Best regards
