### ISSUE TITLE
Feature Vector Visualizing and Matching

### ISSUE THREAD

**Issue by roaasoloh** [libigl/libigl-python-bindings#42]
Hi,
Thank you for this efficient library,

Kindly I have a question please,
I'm trying to work on key points of a mesh, in order to faster the work, what I checked is that for example, I have to give all vertices and faces in order to obtain principal_curvature, is there any way to get for only my desired keypoints(interest points: vertices) from the mesh.

Second, supposing that I'm trying to make a feature vector not only one feature for the point, I mean instead of having for example value [0.342] for vertex [i] I will have vector [0.324 0.1 0.276] for vertex[i], how I may visualize this feature vector?

and the last question please: If I have 2 meshes and I would like to plot them as well plot the keypoints on them, visualizing the matching that is obtained for example using Euclidean distance, is it possible using your library?

Thank you

**Comment by skoch9** [comment]
Hi,
1. There is no direct way of calculating the principle curvature only for certain key points. You could try to hand in a filtered version of your faces array, that only includes all faces around the key points and call the function with the parameters `radius=1, use_k_ring=True`. This uses only the direct neighbours of your keypoints to calculate the principal curvature, so the results might differ.
2. It depends where the 3 values are coming from. If they can be meaningfully mapped to RGB colors, you can directly hand them in to the plot function like `mp.plot(v, f, c=values)`. The `values` array has the same shape as the vertex array `v`. If the direct mapping is not meaningful, you would need to write your own mapping function to translate them to 1 or 3 (RGB) values. Another option would be to visualize them separately in different plots.
3. Sure, you can do something like:
```python
import meshplot as mp
import igl
v1, f1 = igl.read_triangle_mesh("mesh1.obj")
v2, f2 = igl.read_triangle_mesh("mesh1.obj")
p = mp.plot(v1, f1, return_plot=True)
p.add_mesh(v2, f2)
p.add_points(keypoints1)
p.add_points(keypoints2)
p.add_lines(keypoints2 - keypoints1)
```
