### ISSUE TITLE
Please put this on PyPi and make binary wheels

### ISSUE THREAD

**Issue by yig** [libigl/libigl-python-bindings#45]
This repository installs fine on my mac via pip:

    pip3 install 'git+https://github.com/libigl/libigl-python-bindings/#egg=pyigl'

Can you please add it to PyPI and also make binary wheels available? It took a long time to compile. Also, it should specify that `numpy` and `scipy` are dependencies. In a clean environment, the installation failed (after a long compile):

    $ python3 -m venv .venv
    $ . .venv/bin/activate
    $ pip3 install 'git+https://github.com/libigl/libigl-python-bindings/#egg=pyigl'
    ...
    ModuleNotFoundError: No module named 'numpy'

I will open a pull request to add `install_requires=[ 'numpy', 'scipy' ]` to `setup.py`'s `setup()` function.

**Comment by teseoch** [comment]
currently, we are supporting binary trough conda-forge

in the future (when the main development will be stable) we might consider Pip
In general, we are trying to avoid multiple builds because of the overhead.
Conda uses CI to generate the binaries which make development easier

**Comment by gonzalocasas** [comment]
+1 to bringing this to pip. We are unable to define the requirements properly for our package because pushing it to pip complains that it cannot have a direct dependency:

![image](https://user-images.githubusercontent.com/933277/113716743-3116f080-96eb-11eb-8c92-e3ff42e8e4fb.png)

/cc @joburger

**Comment by caniko** [comment]
I am using poetry in my project, and actually considering using `libigl`. The fact that it isn't available through pip forces me to step outside of poetry. Please fix. You can generate binaries using https://github.com/pypa/cibuildwheel

Please consider!

**Comment by teseoch** [comment]
this seems reasonable, I will add it to my todo list for the next release!

**Comment by mboisson** [comment]
Conda can use pip, pip can't use conda. The choice is easy, move default to pypi.
