### ISSUE TITLE
505_MIQ bindings

### ISSUE THREAD

**Issue by arpastrana** [libigl/libigl-python-bindings#50]
Hi all. Are there already bindings for all the functions used in example 505_MIQ of libigl's tutorials section? I would like to try it out in Python. Secondly, is there a forum where I could possibly follow up on questions like this? Many thanks!

**Comment by danielepanozzo** [comment]
Hi, no, and we are not planning to add them due to the dependency on the solver Comiso (which is difficult to compile on conda and it has a viral license). If you have questions the best way is to open issues as you just did.
