### ISSUE TITLE
how to save resulting mesh after plot()

### ISSUE THREAD

**Issue by raghavgurbaxani** [libigl/libigl-python-bindings#51]
hi 

I am following the tutorial provided on the website and I am trying to save the mesh after the plot() function, how do I save the mesh after applying transformations 

ideally save the file in the format save(v,f,c) instead of having a .html output

**Comment by skoch9** [comment]
Hi,
you can just call `igl.write_triangle_mesh(filename, v, f)`.

**Comment by raghavgurbaxani** [comment]
thanks

but that wouldnt save the visualization of the triangle mesh colors , right
?
similar to the ones generated on the .html page

Thank you again for your help.

**Comment by skoch9** [comment]
No, to also save the colors you can call `write_off(filename, v, f, c)` or write your own function.

**Comment by raghavgurbaxani** [comment]
I tried i`gl.write_off('out.off',v,f,c)` but it doesnt save the visualized colors as in the html file, perhaps need to write my own function. 

Is there no other way to save the visualized colored figure ?

**Comment by skoch9** [comment]
It should work, I just tried it:
```python
igl.write_off('out.off', v, f, c)
v1, f1, c1 = igl.read_off("out.off")
print(np.allclose(v, v1), np.allclose(f, f1), np.allclose(c, c1))
```
prints out `True True True`.
