### ISSUE TITLE
random_points_on_mesh returns out of bounds face_ids 

### ISSUE THREAD

**Issue by maria-korosteleva** [libigl/libigl-python-bindings#56]
random_points_on_mesh returns face ids that equal the total face count
A similar issue exists in c++ libigl: https://github.com/libigl/libigl/issues/1531

Reproducing: 
```
import igl

verts, faces = igl.read_triangle_mesh('D:/Data/mesh.obj')
num_samples = 1000
print(len(faces))

for i in range(100):
    _, face_ids = igl.random_points_on_mesh(num_samples, verts, faces)
    for fid in face_ids:
        if not (fid < len(faces) and fid >= 0):
            print('Failed try {} with face {}'.format(i, fid))
```
Output:
```
14886
Failed try 24 with face 14886
Failed try 31 with face 14886
Failed try 58 with face 14886
Failed try 62 with face 14886
```

System info: 
igl 2.2.0
Python 3.6
Windows 10

**Comment by teseoch** [comment]
could you share the mesh?

**Comment by maria-korosteleva** [comment]
No problem, here it is

[mesh.zip](https://github.com/libigl/libigl-python-bindings/files/4876295/mesh.zip)

**Comment by teseoch** [comment]
hmhmh it seems to be a windows problem?

I tried your code/mesh and no error.
If the problem is in the C++ version, it needs to be fixed there.

**Comment by maria-korosteleva** [comment]
Unfortunately, I'm not sure how to check either of your thoughts, whether it's a windows-specific problem, or it's in c++ version. These questions needs someone with a better understanding of libigl-python-bindings that mine. I'd be happy to provide any extra info upon request though. 

I did an additional check if shifting all the output face ids by one could be a workaround, but no, the generator does produce faces with id = 0: 
Code
```
import igl

verts, faces = igl.read_triangle_mesh('D:/Data/mesh.obj')
num_samples = 1000
print(len(faces))

for i in range(100):
    _, face_ids = igl.random_points_on_mesh(num_samples, verts, faces)
    for fid in face_ids:
        if not ((fid-1) < len(faces) and (fid-1) >= 0):
            print('Failed try {} with face {}'.format(i, fid))
```

Output: 
```
14886
Failed try 18 with face 0
Failed try 44 with face 0
Failed try 45 with face 0
Failed try 93 with face 0
Failed try 94 with face 0
Failed try 98 with face 0
```

**Comment by teseoch** [comment]
I think it is a bug in libigl.

Btw, why are you doing `fid-1`?
Shouldn't be just `fid`?

**Comment by maria-korosteleva** [comment]
@teseoch do you mean c++ version libigl? Were you able to reproduce then? 

Regarding `fid-1`, that was an extra check if the whole range of produced face ids was shifted by one. Say, instead of giving face ids in the correct range of `[ 0, len(faces) )` it gives faces in range `[ 1, len(faces)+1 )`. If that was the case, doing `fid-1` will give a workaround

The check confirmed that `igl.random_points_on_mesh()` produces faces ids in range `[ 0, len(faces)+1 )`, so doing `fid-1` won't help

**Comment by teseoch** [comment]
yes the problem is inside the c++, also confirmed by the issue you mentioned.

regarding the -1, got it, makes sense but is it not a fix.
I tried to push Alec to fix the issue, but it seems stuck :(

The fix suggested in the other issue is `FI(i) = FImax;` you can do that in python, just set
```
face_ids[face_ids >= len(faces)] = len(faces)-1
```
or something similar.

I don't think this is the correct fix, but it is a reasonable walk around.
