### ISSUE TITLE
Heat Method For Fast Geodesic Distance Approximation

### ISSUE THREAD

**Issue by cheng-chi** [libigl/libigl-python-bindings#57]
I'm quite interested in [Heat Method For Fast Geodesic Distance Approximation](https://libigl.github.io/tutorial/#heat-method-for-fast-geodesic-distance-approximation). However, it's libigl implementation 
```
igl::heat_geodesics_precompute
igl::heat_geodesics_solve
igl::intrinsic_delaunay_cotmatrix
```
is currently not available with python binding.
Do we have any plan for wrapping these functions? If not, I can give it a try

**Comment by teseoch** [comment]
We are finalizing an instruction page on the website
