### ISSUE TITLE
Boundary loop c++ equivalent 

### ISSUE THREAD

**Issue by pavan4** [libigl/libigl-python-bindings#58]
Hello, 

Is there a reason a c++ equivalent to the `boundary_loop` function is not present in `python` bindings which returns the index's of all the loops? E.g.,

For c++ equivalent of this function ([Implementation](https://github.com/libigl/libigl/blob/3cb4894eaf8ea4610467189ca292be349425d44b/include/igl/boundary_loop.cpp#L16)) is missing in python bindings 
```
 template <typename DerivedF, typename Index>
  IGL_INLINE void boundary_loop(
    const Eigen::MatrixBase<DerivedF>& F, 
    std::vector<std::vector<Index> >& L);
```

only c++ equivalent of 
```
template <typename DerivedF, typename DerivedL>
  IGL_INLINE void boundary_loop(
    const Eigen::MatrixBase<DerivedF>& F, 
    Eigen::PlainObjectBase<DerivedL>& L);
```
is provided in python bindings here :
https://github.com/libigl/libigl-python-bindings/blob/1348a07eb8d1884fd19f7f514442a2c061b30470/src/boundary_loop.cpp#L38

**Comment by teseoch** [comment]
Sorry, I don't understand the question :)

The two `boundary_loop` are: one for a vector and one for a matrix.

In the bindings, we expose only the one for the matrix (which returns a `NumPy` array, ie a matrix).
If you want/need a list of lists you can convert it python side.
The way to call it is
```
l = igl.boundary_loop(f)
```

**Comment by pavan4** [comment]
Sorry I might have asked this a convoluted way :( 

The first function I was referring to returns all the loops found in the mesh [here](https://github.com/libigl/libigl/blob/3cb4894eaf8ea4610467189ca292be349425d44b/include/igl/boundary_loop.h#L24), while the second function returns only the longest loop [here](https://github.com/libigl/libigl/blob/3cb4894eaf8ea4610467189ca292be349425d44b/include/igl/boundary_loop.h#L55)

I would like to fetch all the loops instead of the longest loop.

**Comment by teseoch** [comment]
got it!

Probably overlook while doing the bindings.
Just pushed the new function `all_boundary_loop`, it might take a while to be integrated in Conda.
https://github.com/libigl/libigl-python-bindings/commit/4d80ed847f4cf26c2cab0e0e4701b242e9f5adca

If it is urgent, you can compile the bindings from the source code.

**Comment by pavan4** [comment]
Oh! I was thinking to add this and submit a PR. Wanted to ask first. Thank you 🙏
