### ISSUE TITLE
ARAP energy setting

### ISSUE THREAD

**Issue by wwwslinger** [libigl/libigl-python-bindings#60]
I'm trying to find where in the Python bindings I can set the energy type for the ARAP solver parametrization.  I see it noted in the tutorial, but it is commented out C code, and arap_data is never actually used.  Is it possible to set this anywhere in the Python bindings?

**Comment by teseoch** [comment]
for the moment it uses `ARAP_ENERGY_TYPE_DEFAULT`

**Comment by teseoch** [comment]
I just pushed a change to enable this.
In the next conda release, you will be able to
```
arap = igl.ARAP(v, f, 3, b, igl.ARAP_ENERGY_TYPE_SPOKES)
```

If you need it now, you can try to compile the bindings from source
