### ISSUE TITLE
'module' object has no attribute 'point_mesh_squared_distance'

### ISSUE THREAD

**Issue by sumr4693** [libigl/libigl-python-bindings#61]
Hi,

I installed the igl python binding using conda, and trying to use the function 'point_mesh_squared_distance' like this:
points_to_mesh_dist1, _, _ = igl.point_mesh_squared_distance(cad_v, scan_v, scan_f)
But I am getting the following error:
AttributeError: 'module' object has no attribute 'point_mesh_squared_distance'. 
At the same time, I am able to access the other function such as 'read_triangle_mesh'.

Please help me. Thanks in advance!

**Comment by teseoch** [comment]
which version of igl are you using?
I just tried and with v2.2 and i have the function

**Comment by sumr4693** [comment]
I am very sorry for my late reply. I am using igl-0.1 and anaconda2. For the time being, I am using C++ to use that function. But can you please tell me how to upgrade to v2.2 with conda install command? Thank you!

**Comment by teseoch** [comment]
I am never sure how to update packages, you might try this
https://docs.conda.io/projects/conda/en/latest/commands/update.html

Another way might be just `conda install igl` and it should update it. When you run either command check if something new gets installed

**Comment by sumr4693** [comment]
Thank you very much!
