### ISSUE TITLE
ARAP data member access

### ISSUE THREAD

**Issue by TerranRush** [libigl/libigl-python-bindings#62]
Is it possible to enable the access of data members of ARAP, e.g., the "max_iter," for better control?

**Comment by teseoch** [comment]
I can add them.

This is the full list of stuff inside ARAP data
```
n, G, energy, with_dynamics, f_ext, vel, h, ym, max_iter, K, M, solver_data, b, dim
```
`energy` is there and I think only `with_dynamics, h, ym, max_iter` might need to be exposed.
Is this what you have in mind?

**Comment by teseoch** [comment]
I pushed the change, it will be in conda in the next release

https://github.com/libigl/libigl-python-bindings/commit/fdbbf2ca10946b185477b72ab348c306fdf01b24
