### ISSUE TITLE
ARAP problem

### ISSUE THREAD

**Issue by geomlee** [libigl/libigl-python-bindings#63]
Hello, I want to know if there is a limit on the number of iterations ( like the variation max_iter ).

Because I saw the code `  // Initialize ARAP
  arap_data.max_iter = 100;` 
in `libigl/tutorial/503_ARAPParam/main.cpp`, and I didn't see it in python codes.

So if the max_iter exists in ARAP (python), I want to know how to change it.
Thanks!!!

**Comment by teseoch** [comment]
yes and no :)

in the current conda version, no. In the dev (that needs to be build from source) yes.

We might push to conda soon (~1 month)
