### ISSUE TITLE
ray_mesh_intersect

### ISSUE THREAD

**Issue by fmu2** [libigl/libigl-python-bindings#65]
I got confused by what ray_mesh_intersect does exactly. I thought it should return the point(s) at which a ray and a mesh intersects. I tried this function on bunny_small.off with source = [-1, -1, -1] and dir = [1, 1, 1], the same setting as in the test file, and it returned 1676 hits. Why could there be so many hits? If this is indeed expected, how should I interpret the result? Thanks!

**Comment by teseoch** [comment]
> hits  **sorted** list of hits: id, gid, u, v, t
If you need the closest one, just use the first one.

Regarding the large number of hits, I suppose it is a degenerate case not handled
