### ISSUE TITLE
Function all_boundary_loop not available

### ISSUE THREAD

**Issue by ThomasAuzinger** [libigl/libigl-python-bindings#67]
When trying to use the function `all_boundary_loop` (as defined in [boundary_loop.cpp#71](https://github.com/libigl/libigl-python-bindings/blob/4d80ed847f4cf26c2cab0e0e4701b242e9f5adca/src/boundary_loop.cpp#L71)), I get the error message
`AttributeError: module 'igl' has no attribute 'all_boundary_loop'`.

Strangely, this function is also not listed in the documentation (see [libigl-python-bindings/igl_docs/#functions](https://libigl.github.io/libigl-python-bindings/igl_docs/#functions)) although it is defined in the code file mentioned above and also takes part in the basic tests (see [test_basic.py#L554](https://github.com/libigl/libigl-python-bindings/blob/d209694c501be6049d12b7e9eddc1943275c50d1/tests/test_basic.py#L554).

How would I be able to use this function?

**Comment by BruegelN** [comment]
Which version are you using?
```conda list igl```
Latest version is 2.2.1 from 11 days ago.

Before (e.g. version 2.2.0) it was called `l=boundary_loop(f)`: https://github.com/libigl/libigl-python-bindings/blob/2.2.0/src/boundary_loop.cpp

**Comment by alecjacobson** [comment]
The `igl.all_boundary_loop` function appears to work correctly for me, so I'm guessing this is out of date. Feel free to reopen if still an issue.
