### ISSUE TITLE
2.2.1 via conda?

### ISSUE THREAD

**Issue by welch** [libigl/libigl-python-bindings#68]
running `conda install -c conda-forge igl` as the README advises does not bring in igl! 

It did update a coupla things (conda and certifi-2020), but nothing more.
I am doing this after having previously pip installed the 2.2.0 version, and
pip uninstalled it before attempting the conda approach to get 2.2.1 with
its ARAP improvements.

**Comment by teseoch** [comment]
have you tried `conda update`?
with `conda list` you should be able to see the installed packages

**Comment by welch** [comment]
igl is not installed, and `conda search igl` returns nothing relevant.
meanwhile, the upgrade to conda during the igl install attempt 
is behaving weirdly, need to see if i can back that out.

**Comment by welch** [comment]
looks like i can't have possibly used pip to install 2.2.0, 
though it seemed to claim ownership. 
let's suppose that was via conda, and pip happily did
something when I pip uninstalled igl. yeesh.

**Comment by welch** [comment]
all good after reverting conda, 2.2.1 installed and imports, 
am fine never knowing what just happened there...
