### ISSUE TITLE
Cannot open file on Windows

### ISSUE THREAD

**Issue by eliemichel** [libigl/libigl-python-bindings#71]
```python
>>> import igl, os
>>> print(f"file exist? {os.path.isfile('test.obj')}")
>>> igl.read_obj("test.obj")
file exist? True
---------------------------------------------------------------------------
Traceback (most recent call last)
<ipython-input-17-2e26593b2c0b> in <module>
      1 import igl, os
      2 print(f"file exist? {os.path.isfile('test.obj')}")
----> 3 igl.read_obj("test.obj")

ValueError: File 'test.obj' not found.
```

I tried absolute, relative, forward slashes, backward slashes.
Freshly built from master using `python setup.py`, Python 3.8.6 on Windows 10.

**Comment by teseoch** [comment]
could you share your obj, it might be that the error message is wrong and igl cannot read the format because of an error inside

**Comment by eliemichel** [comment]
Indeed the problem is object specific, here is the faulty one:
[test.zip](https://github.com/libigl/libigl-python-bindings/files/5511519/test.zip)

Note that my process was pretty standard, namely I opened Blender, created a monkey object and exported the scene as an OBJ, period.

**Comment by teseoch** [comment]
Sorry for the late reply. It works for me (as expected) since it is a vanilla file.

Could it be the file is locked or not readable?

**Comment by eliemichel** [comment]
I was trying on another machine to double check and got a new problem, see #74

**Comment by teseoch** [comment]
Have you tried (in python)
```
with open("test.obj", "r") as f:
     # something
```

to check if the file is readable?

**Comment by eliemichel** [comment]
Yes a simple "open" works, but actually I have a bit more info this time:

```
>>> with open("test.obj", "r") as f:
...   print("ok")
...
ok
>>> igl.read_obj("test.obj")
Warning: readOBJ() ignored non-comment line 4:
  o Suzanne
Failed to cast F to matrix: min (3) != max (4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: File 'test.obj' not found.
```

This "Failed to cast F to matrix: min (3) != max (4)" may well be a hint.

**Comment by teseoch** [comment]
are you reading a quad mesh?

**Comment by eliemichel** [comment]
Indeed, my bad. The error message should really be fixed anyways, this is misleading enough to have lead me to clearly wrong hypotheses during my debugging.
