### ISSUE TITLE
Build step for pybind11 failed

### ISSUE THREAD

**Issue by eliemichel** [libigl/libigl-python-bindings#74]
Hello,

I tried installing this module from source using the following:

```
git clone https://github.com/libigl/libigl-python-bindings
cd libigl-python-bindings
git checkout 2.2.1  # also tried master
python setup.py install
```

But compilation fails. 
The core error seems to be "Build step for pybind11 failed: 1", full log: [libigl-python-binding.log](https://github.com/libigl/libigl-python-bindings/files/5610421/libigl-python-binding.log).

(Windows 10, Python 3.8.3)

**Comment by teseoch** [comment]
Strange, this is something inside numpyeigen.
Also strange the it builds on the CI (maybe something on pybind11 changed in the last 3 days?)
@fwilliams can we update to the latest version of pybind11 (I see that you forked the repo)?

I checked the code, and it all looks ok, any other idea?

**Comment by alecjacobson** [comment]
closing this old issue. The build has changed since. Reopen if still an issue.
