### ISSUE TITLE
igl.ARAP can not support dimension 2

### ISSUE THREAD

**Issue by yenlianglintw** [libigl/libigl-python-bindings#81]
I set the dimension parameter to 2 in the function ARAP and pass a [#vertices, 2] array v:
arap = igl.ARAP(v, f, 2, b)

But it shows an error:
Invalid mesh vertices, v must have shape [#vertices, 3] but got v.shape = [502, 2]

I used the version 2.2.1 for igl

Thanks

**Comment by teseoch** [comment]
Thank you! This is a bug, fixed here:
https://github.com/libigl/libigl-python-bindings/commit/7d988864468a002c614d1dd216dd19d4d27dbde3

Will be available in the next release
