### ISSUE TITLE
How to compute an "integral" of a function over the mesh?

### ISSUE THREAD

**Issue by paddyroddy** [libigl/libigl-python-bindings#84]
Apologies if this is obvious, but I can't find anything in the docs/tutorial.

I'm transferring methods in the spherical setting to general manifolds. Say I had some function `f` defined on the sphere and I wanted to compute it's integral i.e. 
![image](https://user-images.githubusercontent.com/15052188/111508710-ec2f1800-8743-11eb-84fe-c0d43d1b3515.png)
The sphere is discretised in `\theta` and `\phi`. Then to compute the integral I'd multiply `f` by `\sin{\theta}` and the gap between the samples i.e. `d\theta`/`d\phi`.

Say I have some function `f` defined on the mesh (`3485` vertices/`6966` faces) i.e.
```
v, t = igl.read_triangle_mesh("bunny.off")
l = -igl.cotmatrix(v, t)
d, u = eigsh(l, 10, sigma=0, which="LM")
f = u[:, 0]
```
This function `f` has length `3485` so is obviously defined on the vertices. But I'm not sure how to compute an integral in this way.

One idea we had was to use `igl.average_onto_faces` so now our function `f_faces` has length `6966`. Then compute the area of each triangle using `igl.doublearea`. Then compute the dot product of these two
```
f_faces = igl.average_onto_faces(t, f)
area = igl.doublearea(v, t) / 2
integral = np.dot(f_faces, area)
```

Is there a better built-in way? If not, are there any obvious problems with this approach? Thanks

**Comment by Sin-tel** [comment]
To compute integrals of a function that you sampled on the vertices, just multiply with the mass matrix and sum the result.

**Comment by paddyroddy** [comment]
ah okay, thank you! I'm new to this area
