### ISSUE TITLE
Docs: unspecified unsigned int type requirement

### ISSUE THREAD

**Issue by PurpleSensation** [libigl/libigl-python-bindings#86]
Hi, I just spent a full morning to find out that the function point_in_poly() requires unsigned values as input. I might learn a bit about GitHub and suggest additions to the Docs. I've been working with the python bindings for a year and the documentation needs some polish.

**Comment by teseoch** [comment]
The doc comes directly from the comments in the C++ version

to make changes in git, 
fork the repo (there is a button), 
create a branch
make your change and push.
On github a new button with pull request will appear, make the pull request and it will appear here
if good, I can then merge it to the main code
