### ISSUE TITLE
Screenshots for the plotting meshes

### ISSUE THREAD

**Issue by xjh19971** [libigl/libigl-python-bindings#87]
Hi libigl-python,

Thank you for this amazing package! I find it a very useful tool.

I have one question: Is there any method to capture the screenshots for the meshes? To be specific, I just want to transfer the uv plane to a PNG image. I think a similar implementation in libigl is 
```
viewer.core.draw_buffer(viewer.data(),false,R,G,B,A)
```
Thank you!

**Comment by teseoch** [comment]
The python bindings of libigl don't support any visualization, you should check meshplot/plotly/matplotlib.
