### ISSUE TITLE
Documentation for igl.principal_curvature(): output order is incorrect

### ISSUE THREAD

**Issue by mihamerstan** [libigl/libigl-python-bindings#88]
The documentation for [principal curvature](https://github.com/libigl/libigl-python-bindings/blob/a732ec6c988fb45e632ceaef2faffd2d3ce5022a/src/principal_curvature.cpp) states that the output is:
pd1, pd2, pv1, pv2 = principal_curvature(v, f)

where pd1 and pv1 are maximal direction and value, respectively, and pd2 and pv2 are the corresponding minimals. The function, however, returns them in the opposite order:

pd2, pd1, pv2, pv1 = principal_curvature(v, f)

An easy test is simply to compare the values.

**Comment by jiangzhongshi** [comment]
Hi Michael,

This is fixed recently https://github.com/libigl/libigl/pull/1767
