### ISSUE TITLE
bad assertion in bbw

### ISSUE THREAD

**Issue by Aixile** [libigl/libigl-python-bindings#90]
L137 asserts `V.cols() == 3`
https://github.com/libigl/libigl-python-bindings/blob/master/classes/classes.cpp#L137 
However, L144 asserts `V.cols() == 2` and there is even no `v_init` in the bbw class.
https://github.com/libigl/libigl-python-bindings/blob/master/classes/classes.cpp#L144-L148
I think the latter assertion shoud be removed

**Comment by teseoch** [comment]
hmhmh you think that `V.cols()` should always be 3 even for a tri mesh?

**Comment by Aixile** [comment]
I think you misunderstanding the problem.

The major problem is if 2D triangle meshes (`V.cols()` is 2), the program will definitely raise an exception on L137, and L144 will not even get executed.
For 3D triangle meshes  (`V.cols()` is 3), the program will raise an exception on L144.
L133 and L144 are contradictory. 

For a tri mesh, I think BBW can work on both 2D planar meshes (`V.cols() == 2`)  and 3D surface meshes   (`V.cols() == 3`).

**Comment by teseoch** [comment]
thanks for the PR, merged!
