### ISSUE TITLE
read_stl function does not exist

### ISSUE THREAD

**Issue by caniko** [libigl/libigl-python-bindings#91]
The function `read_stl` is mentioned in the documentation, but is nowhere to be found, not even in the package:
![image](https://user-images.githubusercontent.com/29519599/120690505-d3a5e280-c494-11eb-8f9f-e224ae13632c.png)

**Comment by teseoch** [comment]
yeah, we decided to wrap only the `read_triangle_mesh` the documentation is wrong.

If you want to read the stl just use `read_triangle_mesh`. I removed the line from the doc
https://github.com/libigl/libigl-python-bindings/commit/deaf5cdd499f62a0515f47e380e0f6971e8ad34e
