### ISSUE TITLE
igl.cotmatrix(V, F) causes process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by WNZhao1988** [libigl/libigl-python-bindings#93]
When I run igl.cotmatrix(V, F), it only shows this error message "igl.cotmatrix(V, F) causes process finished with exit code 139 (interrupted by signal 11: SIGSEGV)" without any other information. Has any one know the reason for this error? I could run igl.grad(V, F) without any porblem.

**Comment by teseoch** [comment]
can you share the data, V, F possibly pickled?
