### ISSUE TITLE
Copyright/left marching cubes status?

### ISSUE THREAD

**Issue by kpasko** [libigl/libigl-python-bindings#94]
Saw some months back that marching cubes had been moved out of copyleft, is there an estimate when it will be available in the py bindings?

**Comment by daviesthomas** [comment]
Not in master yet (and not in conda package) but if you want this functionality "today" you can clone this PR: https://github.com/libigl/libigl-python-bindings/pull/76

And install directly (ideally in pipenv or similar) with
``` python setup.py install ```

Unsure of timeline from PR --> Conda, but this method will atleast get you the functionality required!

**Comment by kpasko** [comment]
Great, thank you for the info!
