### ISSUE TITLE
Better support for STL files, and other mesh formats that don't store the connections between vertices

### ISSUE THREAD

**Issue by caniko** [libigl/libigl-python-bindings#96]
From what I understand in #54, STL files are not supported by at least some of the function in the library including `principal_curvature`.

I do understand that it is possible to make it work with the use of `remove_duplicate_vertices`, which didn't work for me, but might work for others.

Meshlab and Blender seems to solve this problem during import as there are no vertex duplicates in the STL meshes that I have worked with. Moreover, Meshlab can even compute the curvatures of the vertices of meshes generated from STL format.

There should a feature to do a similar import in `igl`. If users want to use the old method they should with the use of a `kwarg` or another function.

Below I combine the import method from meshlab with IGL to compute minimum curvature:
```
import igl
import pymeshlab
import numpy as np
import meshplot as mp
from meshplot import plot


mp.offline()

ms = pymeshlab.MeshSet()
ms.load_new_mesh(<STL path>)

mesh = ms.current_mesh()
v = mesh.vertex_matrix()
f = mesh.face_matrix()

v1, v2, k1, k2 = igl.principal_curvature(v, f)

min_curvature = np.zeros_like(k1)

k1_greater_k2 = k1 > k2
min_curvature[k1_greater_k2] = k2[k1_greater_k2]
k2_greater_k1 = k2 > k1
min_curvature[k2_greater_k1] = k1[k2_greater_k1]

plot(v, f, min_curvature)
```

**Comment by teseoch** [comment]
This is an igl issue, the bindings just expose functionalities to python.

For mesh io, I use meshio :) https://github.com/nschloe/meshio

**Comment by alecjacobson** [comment]
This is an old closed issue but folks still might end up here. 

> **.STL** files do not store meshes. They store a stream of disconnected triangles. libigl loads this literally into `V`, `F`. To connect triangles to mesh, it is correct to call `igl.remove_duplicate_vertices`

Other libraries may do this on load (e.g., MeshLab's GUI has a checkbox).

The OP alluded to issues with `igl.remove_duplicate_vertices`. If there is an issue with that then this should be reopened. It appears to work fine as far as I can tell:

```python
import igl
from meshplot import plot
import numpy as np

v,f = igl.read_triangle_mesh('/Users/ajx/Downloads/armadillo.stl')

v,I,J,f = igl.remove_duplicate_vertices(v,f,0)

v1, v2, k1, k2 = igl.principal_curvature(v, f)

min_curvature = np.zeros_like(k1)

k1_greater_k2 = k1 > k2
min_curvature[k1_greater_k2] = k2[k1_greater_k2]
k2_greater_k1 = k2 > k1
min_curvature[k2_greater_k1] = k1[k2_greater_k1]

plot(v,f,min_curvature)
```

<img width="633" alt="image" src="https://user-images.githubusercontent.com/2241689/216776171-7c7571a5-2976-4ba3-b57f-149a988a18c5.png">
