### ISSUE TITLE
Feature request for Mesh class: Merge adjacent faces that are coplanar; afterwards, remove unreferenced vertices

### ISSUE THREAD

**Issue by caniko** [libigl/libigl-python-bindings#97]
**Is your feature request related to a problem? Please describe.**
I have a mesh where there are many coplanar faces that are adjacent, and I need them removed from my mesh.

**Describe the solution you'd like**
A function that accepts vertices, faces and angle tolerance, and returns a new set of vertices and faces. The changes to the mesh should be printed out.

**Describe alternatives you've considered**
The solution is already implemented in Blender; however, running Blender inside a script is highly unstable. How to replicate in Blender:
Decimate modifier select "Planar" then apply.

Link to the [source from Blender](https://code.it4i.cz/blender/blender-embree3/-/blob/b07ee4e3a5ffa2b28dbd1add7b61d44fc1f2f482/source/blender/bmesh/operators/bmo_dissolve.c#L480).

I submitted a copy of the same [issue](https://github.com/intel-isl/Open3D/issues/3719) to Open3D.

**Comment by teseoch** [comment]
Is this function present in the C++ version?

**Comment by alecjacobson** [comment]
This sounds like a cool feature request for [libigl](https://github.com/libigl/libigl/), which if merged could be result in a python binding here. Note, igl has extremely limited support for general polygon meshes, so once this mesh is built there will not be a lot more that igl could do with it.

I'm closing this issue, but feel free to make the feature request at https://github.com/libigl/libigl/issues
