### ISSUE TITLE
Can I manually install libigl and numpyeigen independently before this libigl-python-binding?

### ISSUE THREAD

**Issue by jiapei100** [libigl/libigl-python-bindings#99]
Can I manually install libigl and numpyeigen independently before this libigl-python-binding? It looks **libigl-python-bindings** download two **external** packages 
- libigl
- numpyeigen
automatically, from within **CMakeLists.txt** I can tell.
However, what if I've already manually installed both packages before this **libigl-python-bindings** ???

Cheers

**Comment by teseoch** [comment]
This requires changing the cmake in a non-trivial way.

We think that most users will not compile the bindings from source, but getting the pre-compiled binaries from conda-forge.

**Comment by alecjacobson** [comment]
Closing this old issue. My understanding is that the answer is: "probably but we're not supporting that".
